/** Common ICD-10 codes for clinical diagnosis lookup (seed data). */
const ICD10_CODES = [
  { code: 'M54.5', description: 'Low back pain' },
  { code: 'M51.26', description: 'Other intervertebral disc displacement, lumbar region' },
  { code: 'I10', description: 'Essential (primary) hypertension' },
  { code: 'E11.9', description: 'Type 2 diabetes mellitus without complications' },
  { code: 'J06.9', description: 'Acute upper respiratory infection, unspecified' },
  { code: 'J18.9', description: 'Pneumonia, unspecified organism' },
  { code: 'R50.9', description: 'Fever, unspecified' },
  { code: 'R51', description: 'Headache' },
  { code: 'R10.9', description: 'Unspecified abdominal pain' },
  { code: 'R05.9', description: 'Cough, unspecified' },
  { code: 'R11.0', description: 'Nausea' },
  { code: 'R11.2', description: 'Nausea with vomiting, unspecified' },
  { code: 'K21.9', description: 'Gastro-esophageal reflux disease without esophagitis' },
  { code: 'K29.7', description: 'Gastritis, unspecified' },
  { code: 'N39.0', description: 'Urinary tract infection, site not specified' },
  { code: 'J45.909', description: 'Unspecified asthma, uncomplicated' },
  { code: 'E78.5', description: 'Hyperlipidemia, unspecified' },
  { code: 'F41.9', description: 'Anxiety disorder, unspecified' },
  { code: 'F32.9', description: 'Major depressive disorder, single episode, unspecified' },
  { code: 'M79.1', description: 'Myalgia' },
  { code: 'M25.50', description: 'Pain in unspecified joint' },
  { code: 'S09.90XA', description: 'Unspecified injury of head, initial encounter' },
  { code: 'S61.0', description: 'Open wound of finger without damage to nail' },
  { code: 'T14.90', description: 'Injury, unspecified' },
  { code: 'A09', description: 'Infectious gastroenteritis and colitis, unspecified' },
  { code: 'B34.9', description: 'Viral infection, unspecified' },
  { code: 'Z00.00', description: 'Encounter for general adult medical examination without abnormal findings' },
  { code: 'Z23', description: 'Encounter for immunization' },
  { code: 'O80', description: 'Encounter for full-term uncomplicated delivery' },
  { code: 'O26.9', description: 'Pregnancy-related condition, unspecified' },
];

module.exports = { ICD10_CODES };
