const ROLES = {
  FRONT_OFFICE: 'front_office',
  FRONT_OFFICE_SUPERVISOR: 'front_office_supervisor',
  NURSE: 'nurse',
  NURSE_SUPERVISOR: 'nurse_supervisor',
  DOCTOR: 'doctor',
  DOCTOR_SUPERVISOR: 'doctor_supervisor',
  PHARMACIST: 'pharmacist',
  PHARMACY_SUPERVISOR: 'pharmacy_supervisor',
  LAB_TECHNICIAN: 'lab_technician',
  LABORATORY_SUPERVISOR: 'laboratory_supervisor',
  RADIOLOGIST: 'radiologist',
  RADIOLOGIST_SUPERVISOR: 'radiologist_supervisor',
  WARD_SUPERVISOR: 'ward_supervisor',
  WARD_STAFF: 'ward_staff',
  PORTER: 'porter',
  KITCHEN_STAFF: 'kitchen_staff',
  KITCHEN_MANAGER: 'kitchen_manager',
  BILLING_CLERK: 'billing_clerk',
  REVENUE_OFFICER: 'revenue_officer',
  MORTUARY_STAFF: 'mortuary_staff',
  SOCIAL_WORKER: 'social_worker',
  DATA_ANALYST: 'data_analyst',
  SYSTEM_ADMIN: 'system_admin',
  EXECUTIVE: 'executive',
};

const PERMISSIONS = {
  patient: ['create', 'read', 'update', 'delete'],
  vitals: ['create', 'read', 'update', 'delete'],
  consultation: ['create', 'read', 'update', 'delete'],
  prescription: ['create', 'read', 'update'],
  lab_request: ['create', 'read', 'update'],
  lab_result: ['create', 'read', 'update', 'delete'],
  sonar_request: ['create', 'read', 'update'],
  sonar_result: ['create', 'read', 'update', 'delete'],
  ward: ['create', 'read', 'update', 'delete'],
  bed: ['create', 'read', 'update', 'delete'],
  admission: ['create', 'read', 'update'],
  transport: ['create', 'read', 'update'],
  diet: ['create', 'read', 'update', 'delete'],
  meal_plan: ['create', 'read', 'update'],
  billing: ['create', 'read', 'update'],
  revenue: ['create', 'read', 'update'],
  inventory: ['create', 'read', 'update', 'delete'],
  mortuary: ['create', 'read', 'update'],
  social_worker_case: ['create', 'read', 'update'],
  referral: ['create', 'read', 'update'],
  queue: ['create', 'read', 'update', 'push'],
  audit_log: ['read'],
  user: ['create', 'read', 'update', 'delete'],
  facility: ['create', 'read', 'update'],
  analytics: ['read'],
};

// Maps each role to its allowed permissions: { resource: [actions] }
const ROLE_PERMISSIONS = {
  [ROLES.SYSTEM_ADMIN]: {
    patient: ['create', 'read', 'update', 'delete'],
    vitals: ['read'],
    consultation: ['read'],
    prescription: ['read'],
    lab_request: ['read'],
    lab_result: ['read'],
    sonar_request: ['read'],
    sonar_result: ['read'],
    ward: ['create', 'read', 'update', 'delete'],
    bed: ['create', 'read', 'update', 'delete'],
    admission: ['read'],
    transport: ['read'],
    diet: ['read'],
    meal_plan: ['read'],
    billing: ['create', 'read', 'update'],
    revenue: ['create', 'read', 'update'],
    inventory: ['create', 'read', 'update', 'delete'],
    mortuary: ['read'],
    social_worker_case: ['read'],
    referral: ['read'],
    queue: ['create', 'read', 'update', 'push'],
    audit_log: ['read'],
    user: ['create', 'read', 'update', 'delete'],
    facility: ['create', 'read', 'update'],
    analytics: ['read'],
  },
  [ROLES.FRONT_OFFICE]: {
    patient: ['create', 'read', 'update'],
    queue: ['create', 'read', 'push'],
    referral: ['read'],
  },
  [ROLES.FRONT_OFFICE_SUPERVISOR]: {
    patient: ['read'],
    queue: ['read'],
    analytics: ['read'],
  },
  [ROLES.NURSE]: {
    patient: ['read'],
    vitals: ['create', 'read', 'update', 'delete'],
    consultation: ['read'],
    lab_request: ['read', 'update'],
    queue: ['read', 'push', 'update'],
  },
  [ROLES.NURSE_SUPERVISOR]: {
    patient: ['read'],
    vitals: ['read'],
    queue: ['read'],
    analytics: ['read'],
    billing: ['read', 'update'],
  },
  [ROLES.DOCTOR]: {
    patient: ['read'],
    vitals: ['read'],
    consultation: ['create', 'read', 'update', 'delete'],
    prescription: ['create', 'read'],
    lab_request: ['create', 'read'],
    lab_result: ['read'],
    sonar_request: ['create', 'read'],
    sonar_result: ['read'],
    ward: ['read'],
    bed: ['read'],
    admission: ['create', 'read'],
    transport: ['create', 'read'],
    diet: ['create', 'read', 'update', 'delete'],
    inventory: ['read'],
    referral: ['create', 'read'],
    queue: ['read', 'push', 'update'],
  },
  [ROLES.DOCTOR_SUPERVISOR]: {
    patient: ['read'],
    vitals: ['read'],
    consultation: ['read'],
    prescription: ['read'],
    lab_request: ['read'],
    lab_result: ['read'],
    admission: ['read'],
    analytics: ['read'],
    inventory: ['read'],
    queue: ['read'],
    billing: ['read', 'update'],
  },
  [ROLES.PHARMACIST]: {
    patient: ['read'],
    consultation: ['read'],
    prescription: ['read', 'update'],
    inventory: ['create', 'read', 'update', 'delete'],
    referral: ['create', 'read'],
    queue: ['read'],
  },
  [ROLES.PHARMACY_SUPERVISOR]: {
    patient: ['read'],
    consultation: ['read'],
    prescription: ['read'],
    inventory: ['create', 'read', 'update'],
    billing: ['read'],
  },
  [ROLES.LAB_TECHNICIAN]: {
    patient: ['read'],
    consultation: ['read'],
    lab_request: ['read', 'update'],
    lab_result: ['create', 'read', 'update', 'delete'],
    queue: ['read'],
  },
  [ROLES.LABORATORY_SUPERVISOR]: {
    patient: ['read'],
    lab_request: ['read'],
    lab_result: ['read'],
    analytics: ['read'],
    queue: ['read'],
  },
  [ROLES.RADIOLOGIST]: {
    patient: ['read'],
    sonar_request: ['read', 'update'],
    sonar_result: ['create', 'read', 'update', 'delete'],
    queue: ['read'],
  },
  [ROLES.RADIOLOGIST_SUPERVISOR]: {
    patient: ['read'],
    sonar_request: ['read'],
    sonar_result: ['read'],
    analytics: ['read'],
    queue: ['read'],
    billing: ['read', 'update'],
  },
  [ROLES.WARD_SUPERVISOR]: {
    patient: ['read'],
    vitals: ['read'],
    consultation: ['read'],
    ward: ['create', 'read', 'update', 'delete'],
    bed: ['create', 'read', 'update', 'delete'],
    admission: ['read', 'update'],
    transport: ['read'],
    diet: ['read'],
    billing: ['read', 'update'],
  },
  [ROLES.WARD_STAFF]: {
    patient: ['read'],
    vitals: ['read'],
    consultation: ['read'],
    ward: ['read'],
    bed: ['read', 'update'],
    admission: ['read', 'update'],
    transport: ['read'],
    diet: ['read'],
  },
  [ROLES.PORTER]: {
    patient: ['read'],
    transport: ['read', 'update'],
    queue: ['read'],
  },
  [ROLES.KITCHEN_STAFF]: {
    diet: ['read'],
    meal_plan: ['read', 'update'],
    inventory: ['read', 'update'],
  },
  [ROLES.KITCHEN_MANAGER]: {
    diet: ['read'],
    meal_plan: ['create', 'read', 'update'],
    inventory: ['create', 'read', 'update', 'delete'],
  },
  [ROLES.BILLING_CLERK]: {
    patient: ['read'],
    billing: ['create', 'read', 'update'],
    revenue: ['read', 'create', 'update'],
    queue: ['read'],
  },
  [ROLES.REVENUE_OFFICER]: {
    billing: ['read'],
    revenue: ['create', 'read', 'update'],
    analytics: ['read'],
  },
  [ROLES.MORTUARY_STAFF]: {
    patient: ['read'],
    mortuary: ['create', 'read', 'update'],
  },
  [ROLES.SOCIAL_WORKER]: {
    patient: ['read'],
    social_worker_case: ['create', 'read', 'update'],
  },
  [ROLES.DATA_ANALYST]: {
    analytics: ['read'],
    patient: ['read'],
  },
  [ROLES.EXECUTIVE]: {
    analytics: ['read'],
    patient: ['read'],
    user: ['read'],
    revenue: ['read'],
    billing: ['read'],
    queue: ['read'],
    admission: ['read'],
    mortuary: ['read'],
  },
};

module.exports = { ROLES, PERMISSIONS, ROLE_PERMISSIONS };
